### ISSUE TITLE
Missing create todo database when I first setup this example

### ISSUE THREAD

**Issue by windy** [heckpsi-lab/midori-todo-example#2]
➜  midori-todo-example git:(master) rake db:migrate
rake aborted!
Sequel::DatabaseConnectionError: Mysql2::Error: Unknown database 'todo'
/Users/yafeilee/workspace/laboratory/midori-todo-example/Rakefile:39:in `block (2 levels) in <top (required)>'
/Users/yafeilee/.rbenv/versions/2.3.1/bin/bundle:22:in `load'
/Users/yafeilee/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
Mysql2::Error: Unknown database 'todo'
/Users/yafeilee/workspace/laboratory/midori-todo-example/Rakefile:39:in `block (2 levels) in <top (required)>'
/Users/yafeilee/.rbenv/versions/2.3.1/bin/bundle:22:in `load'
/Users/yafeilee/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate

**Comment by dsh0416** [comment]
Currently, it won't create database when migrating. You may need to create it your own. I'm considering creating database automatically in later versions.

**Comment by windy** [comment]
@dsh0416 right, maybe it can support `rake db:create` command
